apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: guestbook
  finalizers:
  # The default behaviour is foreground cascading deletion
  - resources-finalizer.argocd.argoproj.io
  # Alternatively, you can use background cascading deletion
  # - resources-finalizer.argocd.argoproj.io/background
# Add labels to your application object.
labels:
  name: guestbook
spec:
  project: default
  source:
    repoURL: git@github.com:Th3Heavy/app-gestbook
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        name: guestbook
        app: guestbook
        namespace: guestbook