apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 30000 # Optionnel, sinon un port sera attribué automatiquement
  selector:
    app: whoami
