{{- if .Values.ingress.enabled -}}
# Backend IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "skyvern.fullname" . }}
  labels:
    {{- include "skyvern.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoints | default "web" }}
  routes:
    - kind: Rule
      match: HostRegexp(`^skyvern\..+$`) && PathPrefix(`/api`)
      priority: 10
      services:
        - kind: Service
          name: {{ include "skyvern.fullname" . }}
          port: {{ .Values.skyvern.service.port }}
      {{- if .Values.ingress.middlewares }}
      middlewares:
      {{ toYaml .Values.ingress.middlewares | indent 8 }}
      {{- end }}

---
# UI IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "skyvern.ui.fullname" . }}
  labels:
    {{- include "skyvern.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    gethomepage.dev/href: https://skyvern.allapps.me
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Tools
    gethomepage.dev/icon: /icons/skyvern.png
    gethomepage.dev/name: Skyvern
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/weight: "10"
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoints | default "web" }}
  routes:
    - kind: Rule
      match: HostRegexp(`^skyvern\..+$`)
      priority: 1
      services:
        - kind: Service
          name: {{ template "skyvern.ui.fullname" . }}
          port: {{ .Values.skyvernUi.service.port }}
      {{- if .Values.ingress.middlewares }}
      middlewares:
      {{ toYaml .Values.ingress.middlewares | indent 8 }}
      {{- end }}
---
# Artifact IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "skyvern.artifact.fullname" . }}
  labels:
    {{- include "skyvern.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoints | default "web" }}
  routes:
    - kind: Rule
      match: HostRegexp(`^skyvern\..+$`) && PathPrefix(`/artifact`)
      priority: 1
      services:
        - kind: Service
          name: {{ template "skyvern.artifact.fullname" . }}
          port: {{ .Values.skyvernUi.service.artifactPort }}
      {{- if .Values.ingress.middlewares }}
      middlewares:
      {{ toYaml .Values.ingress.middlewares | indent 8 }}
      {{- end }}
{{- end }}
