{{- if .Values.ingress.enabled -}}
# Backend IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "skyvern.fullname" . }}-api
  labels:
    {{- include "skyvern.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoints | default "web" }}
  routes:
    - kind: Rule
      match: PathPrefix(`{{ .Values.ingress.basePath | default "/" }}api`)
      services:
        - kind: Service
          name: {{ include "skyvern.fullname" . }}
          port: {{ .Values.skyvern.service.port }}
      {{- if .Values.ingress.middlewares }}
      middlewares:
      {{ toYaml .Values.ingress.middlewares | indent 8 }}
      {{- end }}
{{- end }}
