{{- if .Values.ingress.enabled -}}
# Backend IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "skyvern.fullname" . }}-api
  labels:
    {{- include "skyvern.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoints | default "web" }}
  routes:
    - kind: Rule
      match: PathPrefix(`/skyvern/api`)
      services:
        - kind: Service
          name: {{ include "skyvern.fullname" . }}
          port: {{ .Values.skyvern.service.port }}
      middlewares:
        - name: strip-prefix
      {{- if .Values.ingress.middlewares }}
      middlewares:
      {{ toYaml .Values.ingress.middlewares | indent 8 }}
      {{- end }}

---
# UI IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "skyvern.ui.fullname" . }}-web
  labels:
    {{- include "skyvern.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoints | default "web" }}
  routes:
    - kind: Rule
      match: PathPrefix(`/skyvern`)
      priority: 1
      services:
        - kind: Service
          name: {{ template "skyvern.ui.fullname" . }}
          port: {{ .Values.skyvernUi.service.port }}
      middlewares:
        - name: strip-prefix
      {{- if .Values.ingress.middlewares }}
      middlewares:
      {{ toYaml .Values.ingress.middlewares | indent 8 }}
      {{- end }}
---
# WebSocket IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "skyvern.ui.fullname" . }}-ws
  labels:
    {{- include "skyvern.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoints | default "web" }}
  routes:
    - kind: Rule
      match: PathPrefix(`/skyvern/api/v1/stream`)
      services:
        - kind: Service
          name: {{ template "skyvern.ui.fullname" . }}
          port: {{ .Values.skyvernUi.service.wsPort }}
      middlewares:
        - name: strip-prefix
      {{- if .Values.ingress.middlewares }}
      middlewares:
      {{ toYaml .Values.ingress.middlewares | indent 8 }}
      {{- end }}
{{- end }}
