apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "skyvern.fullname" . }}-after
  labels:
    {{- include "skyvern.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "skyvern.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
      containers:
        - name: {{ .Chart.Name }}-afte
          image: "busybox:stable"
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              {{- range .Values.job.browserFactory.content }}
              sed -i '/{{ $.Values.job.browserFactory.insertAfter }}/a\{{ . }}' {{ $.Values.job.browserFactory.file }}
              {{- end }}
          securityContext:
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
      restartPolicy: OnFailure
