---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret
  namespace: skyvern
spec:
  encryptedData:
    openai-api-key: AgB7S0utxhGqMpPZn4iOumcrODDPt3RC4P8rMGzQwhLANY/VSLPhIEcafFLz6amlxD1VytD2BAqF7ThmMKCrgazV6ZlrnJPYBIYkaXN0d4XwtUnOVA2O894NqZh7mrx1AwW4J2E7I926BozvRw/S/obpp2RESc+/b4lqfWpKfrz5RGqQITfZDgHdD3lCgC18FRP0awdvQZgmk8wOm3R5eE6jeK9mrzKmKpoq9lDTrqEPITXLXVvde3JaMZwzgxgTRlcsFUimesIYk9gWipA0CRema0VjqqjkGTWqmOFBPfe704SHHQpsAi3QEBZApLRGDITav58EZUrVhm6B+NR13UZBwDK9JGEr1jC/k5LIAHNsWYmkWI28o6+xn2gEYSOjjWruJQ6t4vbWCj3cbsqI+Z1sHSqwZlsV7gvFQ9SaZpGYIepRUVRmnJ+xwjzVaTFTY5J9IFU8fcxgh20hCNASoFGp82eKfCiqrOJvzdq79paadIrWARzKDoV0KJY+kgHX+EJrpw1obe5yOxTkV8oo2oArWB4U/8s+Xb4bsIchv1MsKxJdHHbTvQRSpBBs/lapzxFDnZuagFNHOEMAWm8DDrQ9omVjZBHOHTk+dpHOnOxcQQkAOnbTtSU/AkQyAPP9nQjzuOKjK4hOgyf28m7LUBGo79VCoQTy/XFHNUwbl+xOuiedDMBdhlQgi/qtJnrTeSu+ERwUYVRxdpG7ZH8TE6trZIQXJ+kGrobBljFCu6fRtyD0Mncm+pFyjH7669PBQOQdHbabs0aaOlp/pfjXJrp2z4HIrlYYma5Kar13o8IRAI6jg8DnrWNol5oFTOR1/Q==
  template:
    metadata:
      creationTimestamp: null
      name: secret
      namespace: skyvern
