---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tinyauth
  namespace: tinyauth
spec:
  encryptedData:
    secretKey: AgCePVbE6YA7KFOjicPIh0WzouZSNXgfMInVOoFXfkdQDsh9tgcuK9YJ5LqKplW5BL9ouw/mBK2wz4YDekCkzcJQGWAVkrN/flFkXSjF0mX5bhc2+Mays4SnU/gNpXb83d8OO4eTfRhlHNThByCPFIwVT4MVviPCJdr+p2A9leZuUq09wcy0XbVb0EsCbIKlDLz+MuUWl2YVvueEvowQMxmBLtoFhPzw62qS7CCDKTtsQ8rqwLnW/BEyeoHuFZ56bdVtY3/vYbeza/YBEK75j+A+x4G9VJgvnf4OzeYP46CbPhp0RLpU3KBniKF9DFUlT6CofROo1m7pH3Rs6SjgslGExoiTd01KpECf7/RRKqgwGK0eKIOxVeZ3aTGYm6n4Mf4a9rM4frTaBUYzeJIUBPPNUjnhQOgr77Zq4jh3o/VqWPwjLDMPJudNtnV+E7n8FW2ppkI83d1/flTg9ZekMjhbaGFFCc4ht2QFpIPPf2VKAZNkjH2KDl8PtABS0fktsyUGsTbTHQX3L+aILIbXmtz5pyHzuRXwz0yAmNCd9mXv4QCeIRMlxHffQF1yo1qecB2JCgHBd2SHnhMQyUSOlfRKZFjILHNvkBjjOR9fzRBjg0eHzhZ4Ot4M1/r1hPLzMOYGSc/PZYKKkyi0xGMwtqSetl0MyFQkWKM56NnnaictaY0lPv5tMYWXmPidUyTlIh6cytUfDNHfLNV8YcUtxfAxU9C3
    type: Opaque
