---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tinyauth
  namespace: tinyauth
spec:
  encryptedData:
    secretKey: AgCxohV5mTI1ZFGXbGiPr1FMnnmpHIy/9bVUp0D4pNYadBoMSZy1Ojy8NCkm8hN+I7lAM7na7GdD2Q6nUDFVSBbI8TYYrRevt5Q1qMmHnk79PeGT2WzVy6hVLU5dzcmOWqTRO5eTVOQN99kv4E7PwwUe9LO2C+ZVoGOqVckmA/bBap5SMcc7BdBbtXb0MqIjlYcoYJJAwsjs4ynOQzPg0/8rwg6LDGrJFMGwhiMpaUqqV1uLwUSccSoZzNOjpk0hpUYtRhE1h1//iviF577zTv6h2copIOjjDmFJfhk9TLY71ItO9M9MVBR7iBQ/j0oX3yJPAzc9pk64TuntrXFhL03PDVi1+Yr/JHuZWyFCEY3d8LjSUWyDOWAfRtUC1D5/1bS/pW2ltaLnUjvJUhPj9aYvloPd/1FNoj72VaCxgh+kfSX8DQSFRmsZkq6lQSrrZNafYO1OasI0NuLHkLhUKoknFyrJHdIzI2lnjqiTN1nOha9cTuYWo0W5XIyxiFVdM3ZBw371ivi3wheFy3o5fe+T2vero1dq8NgoMB8S0HxY/0+GYNyAUNyxcip30ie5o+40VdqMJgYwgwL9yWVfj7SShhvraI47Nu9k+8/DCLQRkIdSGZxRGeFF7MpDWhRVe01Q/mgfItnFXPE9UHQ+ENiWt+shqXbDf6uKsbNW8JaXpXxpwr44gdsotl9uL/uOzpCraXjgUr/cXHwmCgtnG1kPNNW6enRv8uRyG8nN
    type: Opaque
