apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ddnsupdater
  namespace: ddnsupdater
  annotations:
    kubernetes.io/ingress.class: traefik
    gethomepage.dev/href: "https://allapps.me/dns"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Tools
    gethomepage.dev/icon: emby.png
    gethomepage.dev/name: "DDNS Updater"
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/weight: "10" # optional
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/dns`)
      services:
      - kind: Service
        name: ddnsupdater
        port: 80
