apiVersion: v1
kind: Service
metadata:
  name: ddnsupdater
spec:
  selector:
    app: ddnsupdater
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30083