apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manager_app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Th3Heavy/argocd
    targetRevision: HEAD
    path: template
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
