apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sealed-secrets
  namespace: sealedsecret
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/secret`)
      services:
      - kind: Service
        name: sealed-secrets
        port: 8080
