apiVersion: apps/v1
kind: Deployment
metadata:
  name: evilginx
  labels:
    app: evilginx
spec:
  selector:
    matchLabels:
      app: evilginx
  template:
    metadata:
      labels:
        app: evilginx
    spec:
      containers:
        - name: evilginx
          image: "{{ .Values.evilginx.image.name }}:{{ .Values.evilginx.image.tag }}"
          ports:
            - containerPort: 8080