apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gophish
  namespace: gophish
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: 'HostRegexp(`^gophish\..+$`)'
      services:
      - kind: Service
        name: gophish
        port: 80
