apiVersion: v1
kind: Service
metadata:
  name: gophish
spec:
  selector:
    app: gophish
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: evilginx
spec:
  selector:
    app: evilginx
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080