apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirlingpdf-copie
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Th3Heavy/argocd.git
    path: stirlingpdf-copie
    targetRevision: HEAD
    helm:
      valueFiles: 
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true