apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}-postgres
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    service: {{ include "n8n.fullname" . }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
      service: {{ include "n8n.fullname" . }}-postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: {{ include "n8n.fullname" . }}-postgres
        {{- include "n8n.labels" . | nindent 8 }}
    spec:
      containers:
        - image: postgres:11
          name: postgres
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.db.service.ports.postgresql }}
          volumeMounts:
            - name: {{ include "n8n.fullname" . }}-postgres
              mountPath: /var/lib/postgresql/data
            - name: {{ template "n8n.fullname" . }}-database-configmap
              mountPath: /docker-entrypoint-initdb.d/init-n8n-user.sh
              subPath: init-data.sh
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata      
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "n8n.fullname" . }}-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "n8n.fullname" . }}-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.db.auth.database | quote }}
            - name: POSTGRES_NON_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "n8n.fullname" . }}-postgres-secret
                  key: POSTGRES_NON_ROOT_USER
            - name: POSTGRES_NON_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "n8n.fullname" . }}-postgres-secret
                  key: POSTGRES_NON_ROOT_PASSWORD
            - name:   POSTGRES_HOST
              value: {{ include "n8n.fullname" . }}-postgres
            - name: POSTGRES_PORT
              value: {{ .Values.db.service.ports.postgresql | quote }}
      restartPolicy: Always
      volumes:
        - name: {{ include "n8n.fullname" . }}-postgres
          persistentVolumeClaim:
            claimName: {{ include "n8n.fullname" . }}-postgres
        - name: {{ template "n8n.fullname" . }}-postgres-secret
          secret:
            secretName: {{ template "n8n.fullname" . }}-postgres-secret
        - name: {{ template "n8n.fullname" . }}-database-configmap
          configMap:
            name: {{ template "n8n.fullname" . }}-database-configmap
            defaultMode: 0744