apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    service: {{ include "n8n.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
      service: {{ include "n8n.fullname" . }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if eq .Values.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    metadata:
      labels:
        service: {{ include "n8n.fullname" . }}
        {{- include "n8n.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chmod 0640 /home/node/.n8n/config"]
          volumeMounts:
            - name: {{ include "n8n.fullname" . }}-pvc
              mountPath: /home/node/.n8n/config
      containers:
        - command:
            - /bin/sh
          args:
            - -c
            - sleep 5; n8n start
          env:
          {{- include "n8n.envVars" . | nindent 12 }}
            - name: DB_TYPE
              value: {{ .Values.db.type | quote }}
            - name: DB_SQLITE_POOL_SIZE
              value: {{.Values.db.sqlitePoolSize | quote }}
            - name: N8N_PROTOCOL
              value: {{ .Values.service.name | quote }}
            - name: N8N_PORT
              value: {{ .Values.service.port | quote }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: {{ include "n8n.worker.name" . }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: {{ include "n8n.fullname" . }}-pvc
            - mountPath: /files
              name: {{ include "n8n.fullname" . }}-host
      restartPolicy: Always
      volumes:
        - name: {{ include "n8n.fullname" . }}-pvc
          persistentVolumeClaim:
            claimName: {{ include "n8n.fullname" . }}
        - name: {{ include "n8n.fullname" . }}-host
          hostPath:
            path: /files_n8n
            type: DirectoryOrCreate