apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    service: {{ include "n8n.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
      service: {{ include "n8n.fullname" . }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if eq .Values.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    metadata:
      labels:
        service: {{ include "n8n.fullname" . }}
        {{- include "n8n.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chown 1000:1000 /data"]
          volumeMounts:
            - name: {{ include "n8n.fullname" . }}
              mountPath: /data
      containers:
        - command:
            - /bin/sh
          args:
            - -c
            - sleep 5; n8n start
          env:
            - name: DB_TYPE
              value: {{ .Values.db.type | quote }}
            - name: DB_POSTGRESDB_HOST
              value: {{ template "n8n.fullname" . }}-postgresql
            - name: DB_POSTGRESDB_PORT
              value: {{ .Values.db.service.ports.postgresql | quote }}
            - name: DB_POSTGRESDB_DATABASE
              value: {{ .Values.db.auth.database | quote }}
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "n8n.fullname" . }}-postgres-secret
                  key: POSTGRES_NON_ROOT_USER
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "n8n.fullname" . }}-postgres-secret
                  key: POSTGRES_NON_ROOT_PASSWORD
            - name: N8N_PROTOCOL
              value: {{ .Values.service.namequote }}
            - name: N8N_PORT
              value: {{ .Values.service.port | quote }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: {{ include "n8n.worker.name" . }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: {{ include "n8n.fullname" . }}
      restartPolicy: Always
      volumes:
        - name: {{ include "n8n.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "n8n.fullname" . }}
        - name: {{ template "n8n.fullname" . }}-secret
          secret:
            secretName: {{ template "n8n.fullname" . }}-secret
        - name: {{ template "n8n.fullname" . }}-postgres-secret
          secret:
            secretName: {{ template "n8n.fullname" . }}-postgres-secret