apiVersion: v1
kind: Secret
metadata:
  name: {{ template "n8n.fullname" . }}-postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres2025
  POSTGRES_DB: {{ .Values.db.auth.database | quote }}
  POSTGRES_NON_ROOT_USER: postgres
  POSTGRES_NON_ROOT_PASSWORD: postgres