apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-postgres
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    service: {{ include "n8n.fullname" . }}-postgres
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.db.service.ports.postgresql }}
      targetPort: {{ .Values.db.service.ports.postgresql }}
      protocol: TCP
      name: postgresql
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
    service: {{ include "n8n.fullname" . }}-postgres
