{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: unleash
  {{- with .Values.ingress.annotations }}
  annotations:
    kubernetes.io/ingress.class: traefik
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoints | default "web" }}
  routes:
    - kind: Rule
      match: 'HostRegexp(`^unleash\..+$`)'
      services:
        - kind: Service
          name: unleash
          port: {{ .Values.ingress.port }}
      {{- if .Values.ingress.middlewares }}
      middlewares:
      {{ toYaml .Values.ingress.middlewares | indent 8 }}
      {{- end }}
{{- end }}