apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 33.2.1
    helm:
      #valuesfile: traefik/values.yaml
      values: |
        service: 
          type: NodePort
        globalArguments:
          - "--global.sendanonymoususage"
        ingressRoute: 
          dashboard: 
            enabled: true
          annotations:
            kubernetes.io/ingress.class: "traefik"
        logs: 
          general: 
            level: "DEBUG"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true



