traefik:
  service: 
    type: NodePort
  ports: 
    web:
      nodePort: 31960
    websecure:
      nodePort: 31961
  globalArguments:
      - "--global.sendanonymoususage=false"
      - "--certificatesresolvers.lol.acme.email=admin@allapps.me"
      - "--certificatesresolvers.lol.acme.storage=/data/acme.json"
      - "--certificatesresolvers.lol.acme.tlschallenge=true"
      - "--certificatesresolvers.lol.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
  providers:  # @schema additionalProperties: false
    kubernetesCRD:
      # -- Load Kubernetes IngressRoute provider
      enabled: false
    kubernetesIngress:
      # -- Load Kubernetes Ingress provider
      enabled: false
  ingressRoute: 
    dashboard: 
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
      entryPoints: ["web"]
      # tls:
      #   xxxx
  logs: 
    general: 
      level: "TRACE"
    access:
      enabled: false
  metrics:
    prometheus: null
  # deployment:
  #   initContainers:
  #     - name: volume-permissions
  #       image: busybox:latest
  #       command: ["sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json"]
  #       volumeMounts:
  #         - name: data
  #           mountPath: /data

