apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 33.2.1
      helm:
        #valuesfile: traefik/values.yaml
        values: |
          service: 
            type: NodePort
          globalArguments:
            - "--global.sendanonymoususage: false"
          ingressRoute: 
            dashboard: 
              enabled: true
            annotations:
              kubernetes.io/ingress.class: "traefik"
          logs: 
            general: 
              level: "DEBUG"
    - repoURL: git@github.com:Th3Heavy/argocd.git
      path: argocd
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty : true 



