apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 33.2.1
    helm:
      values: |
        service: 
          type: NodePort
        ports: 
          web:
            nodePort: 31960
          websecure:
            nodePort: 31961
        globalArguments:
           - --global.sendanonymoususage=false
        ingressRoute: 
          dashboard: 
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "traefik"
            entryPoints: ["web"]
        logs: 
          general: 
            level: "INFO"
          access:
            enabled: false
        metrics:
          prometheus: null
        providers:
          file:
            enabled: true
            content: 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
