apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: changedetection
  namespace: changedetection
  annotations:
    kubernetes.io/ingress.class: traefik
    gethomepage.dev/href: "https://allapps.me/changedetection"
    gethomepage.dev/enabled: "false"
    gethomepage.dev/group: Tools
    gethomepage.dev/icon: changedetection.png
    gethomepage.dev/name: "Change Detection"
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/weight: "10" # optional
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: 'HostRegexp(`^changedetection\..+$`)'
      services:
      - kind: Service
        name: changedetection
        port: 5000