apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: changedetection
  namespace: changedetection
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/changedetection`)
      services:
      - kind: Service
        name: changedetection
        port: 5000
      middlewares:
        - name: changedetection-headers
        - name: changedetection-strip
