apiVersion: v1
kind: Service
metadata:
  name: changedetection
spec:
  selector:
    app: changedetection
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP