apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
data:
  log.level: debug
  git.commit-message-template: |
  build: automatic update of {{ .AppName }}

  {{ range .AppChanges -}}
  updates image {{ .Image }} tag '{{ .OldTag }}' to '{{ .NewTag }}'
  {{ end -}}