apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
data:
  log.level: info
  git.commit-message-template: |
    {{ range .AppChanges -}}
    {{ .AppName }}: updates {{ .Image }} tag '{{ .OldTag }}' to '{{ .NewTag }}'
    {{ end -}}