apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: stirlingpdf
  namespace: stirlingpdf
  annotations:
    kubernetes.io/ingress.class: traefik
    # gethomepage.dev/href: "http://kubeserver:31960/pdf"
    # gethomepage.dev/enabled: "true"
    # gethomepage.dev/description: "Stirling PDF"
    # gethomepage.dev/group: Tools
    # gethomepage.dev/icon: emby.png
    # gethomepage.dev/name: "Stirling PDF"
    # gethomepage.dev/widget.type: "emby"
    # gethomepage.dev/widget.url: "http://kubeserver:31960/pdf"
    # gethomepage.dev/pod-selector: ""
    # gethomepage.dev/weight: "10" # optional
    # gethomepage.dev/instance: "public" # optional
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/pdf`)
      services:
      - kind: Service
        name: stirling-pdf
        port: 8080
      middlewares:
      - name: middleware-headers
      - name: middleware-strip