apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
  annotations:
    kubernetes.io/ingress.class: traefik
    gethomepage.dev/href: "https://allapps.me/pdf"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Tools
    gethomepage.dev/icon: emby.png
    gethomepage.dev/name: "Stirling PDF"
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/weight: "10" # optional
spec: 
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/pdf`)
      services:
      - kind: Service
        name: stirling-pdf
        port: 8080