argo-cd:
  fullnameOverride: argocd
  namespaceOverride: argocd
  global:
    domain: "allapps.me/argocd"
  configs:
    params:
      server.rootpath: "/argocd"
      server.basehref: "/argocd"
      server.insecure: true