apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homarr
  namespace: homarr
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/homarr`)
      services:
      - kind: Service
        name: homarr
        port: 7575
      middlewares:
      - name: middleware-headers
      - name: middleware-strip