---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: homarr
spec:
  encryptedData:
    SECRET_ENCRYPTION_KEY: AgB7L+tbwVdFEHeby8CFbeec4biOqHBpLpoc3PRNp46Wong7gozOnu9kXS6WlQS6ldfCF76Jnq5ESKXRuWnYargJv693VDORt1nTsj9ML7h4WzQOSZUQvs8KhwO4L9FyFJXuY6O4njeMUrNWAGapoKZ2x9xgwBc3/1g1w830r9OzCCUgNfEM5xxLtYjF/NstTzj42fi96ROo6/ReHkJjCxZOacRrfa5DeRxw6f0UdD0XWXp3uZjIrlhlmqqmAh0nyl9vq/yQA33Xq1lS8kXFEKQM5ghrv61lJWgI2EZXi4ygPy7pztailSZKFtYE4iOyyZDX/0snigHn6BhU5hqB/85V0Lpr1r1znj2ItH22YiKC1tcUE6Gf9Mc1yprkTpao6PHCx0U+DhlAbkEuhZpedqXrKRLKkxNpkQgexfzRa39xnLoAXH7dm2UPA6fAmJY6I+y2kXVqCz8Kst2dUWc4bqvYXsuArB20f79IR/tqWQYQ/delHfbE1IYTyFO2jqo93bHeFtwAFBls/oKLU/CXuz99C6rU0HLHeiFkUUMvLCCCwTNCfnmiaDJUzvB1Ygni7Bm9vpra/Q1m+gKxJ4hZd/sUUKxF8YAm2eOzu2mLEEbW+UoY2lCeLRetcG9xp5ZGsr1aqP9BKtQ2f7kLxaUa1ciLJBQ6q8rGvk3QpxFtZy8echp/xeLPTvHxU6dJUpcSxEvFKMZVcexSMLjVc55kfouujePfjNJo9qs16cz44Wa20lK/ADDN/BIAuibRZM+Zm3oWH2nWvMBpkMQWa50u9+Y=
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: homarr
    type: Opaque
