apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddnsupdater
  labels:
    app: ddnsupdater
spec:
  selector:
    matchLabels:
      app: ddnsupdater
  template:
    metadata:
      labels:
        app: ddnsupdater
    spec:
      containers:
        - name: ddns
          image: "{{ .Values.ddns-updater.image.name }}:{{ .Values.ddns-updater.image.tag }}"
          envFrom:
            - secretRef:
                name: ddnsupdater
            - configMapRef:
                name: ddnsupdater
          ports:
            - containerPort: 8000