apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirlingpdf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: stirling-pdf-chart
    repoURL: https://stirling-tools.github.io/Stirling-PDF-chart
    targetRevision: 1.3.1
    helm:
      values: |
        fullnameOverride: stirling-pdf
  destination:
    server: "https://kubernetes.default.svc"
    namespace: stirlingpdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty : true 
    syncOptions:
    - CreateNamespace=true