apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirlingpdf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Th3Heavy/argocd.git
    path: stirlingpdf
    targetRevision: HEAD
    helm:
      valueFiles: 
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: stirlingpdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty : true 
    syncOptions:
    - CreateNamespace=true