apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirlingpdf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: stirling-pdf-chart
      repoURL: https://stirling-tools.github.io/Stirling-PDF-chart
      targetRevision: 1.3.1
      helm:
        values: |
          fullnameOverride: stirling-pdf
          rootPath: /stirlingpdf
    - repoURL: git@github.com:Th3Heavy/argocd.git
      path: stirlingpdf
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: stirlingpdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty : true 
    syncOptions:
    - CreateNamespace=true