apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirlingpdf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # - chart: stirling-pdf-chart
    #   repoURL: https://stirling-tools.github.io/Stirling-PDF-chart
    #   targetRevision: 1.3.1
    #   helm:
    #     valueFiles: 
    #       - values.yaml
    - repoURL: git@github.com:Th3Heavy/argocd.git
      path: stirlingpdf
      targetRevision: HEAD
      helm:
        valueFiles: 
          - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: stirlingpdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty : true 
    syncOptions:
    - CreateNamespace=true