apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: stirling-pdf-chart
    repoURL: https://stirling-tools.github.io/Stirling-PDF-chart
    targetRevision: 1.3.1
    helm:
     # releaseName: stirling-pdf
      values: |
        nameOverride: stirling-pdf
        service:
          externalPort: 80
          type: NodePort
          targetPort: 8080
          nodePort: 31200

  destination:
    server: "https://kubernetes.default.svc"
    namespace: stirling-pdf
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        name: stirling-pdf
        app: stirling-pdf
        namespace: stirling-pdf