apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: stirling-pdf-chart
    repoURL: https://stirling-tools.github.io/Stirling-PDF-chart
    targetRevision: 1.3.1
    helm:
     # releaseName: stirling-pdf
     # values: |
     #   nameOverride: stirling-pdf
  destination:
    server: "https://kubernetes.default.svc"
    namespace: stirling-pdf
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        name: stirling-pdf
        app: stirling-pdf
        namespace: stirling-pdf