apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: changedetection
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    argocd-image-updater.argoproj.io/image-list: changedetection=ghcr.io/dgtlmoon/changedetection.io:~0.49
    argocd-image-updater.argoproj.io/changedetection.helm.image-name: changedetection.image.name
    argocd-image-updater.argoproj.io/changedetection.helm.image-tag: changedetection.image.tag
    argocd-image-updater.argoproj.io/changedetection.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:../changedetection/values.yaml
spec:
  project: default
  source:
    repoURL: git@github.com:Th3Heavy/argocd.git
    path: charts/changedetection
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: changedetection
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true