apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    argocd-image-updater.argoproj.io/image-list: homepage=ghcr.io/gethomepage/homepage:~v0.10
    argocd-image-updater.argoproj.io/homepage.helm.image-name: homepage.image.name
    argocd-image-updater.argoproj.io/homepage.helm.image-tag: homepage.image.tag
    argocd-image-updater.argoproj.io/homepage.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:../homepage/values.yaml
spec:
  project: default
  source:
    repoURL: git@github.com:Th3Heavy/argocd.git
    path: charts/homepage
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: homepage
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true