apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n2
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: git@github.com:Th3Heavy/argocd.git
    path: charts/n8n2
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: n8n2
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true