apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quota-stirling-pdf
spec:
  project: default
  source:
    repoURL: git@github.com:BenLikeCode/argocd.git
    path: charts/app-of-apps/base/quotas/stirlingpdf.yaml
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: stirling-pdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
