apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    argocd-image-updater.argoproj.io/image-list: stirlingpdf=ghcr.io/stirling-tools/stirling-pdf:~v0.37
    argocd-image-updater.argoproj.io/stirlingpdf.helm.image-name: stirlingpdf.image.name
    argocd-image-updater.argoproj.io/stirlingpdf.helm.image-tag: stirlingpdf.image.tag
    argocd-image-updater.argoproj.io/stirlingpdf.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:../stirling-pdf/values.yaml
spec:
  project: default
  source:
    repoURL: git@github.com:Th3Heavy/argocd.git
    path: charts/stirling-pdf
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: stirling-pdf
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true