apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unleash
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: git@github.com:BenLikeCode/argocd.git
    path: charts/unleash
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: unleash
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true