apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: stirling-pdf
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: stirling-pdf
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stirling-pdf
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: SYSTEM_ROOTURIPATH
              value: /pdf
            - name: ALLOW_GOOGLE_VISIBILITY
              value: 'false'
            - name: APP_LOCALE
              value: fr-FR
            - name: SYSTEM_ENABLEANALYTICS
              value: 'false'
          image: "{{ .Values.stirlingpdf.image.name }}:{{ .Values.stirlingpdf.image.tag }}"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /pdf
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: stirling-pdf
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /pdf
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          securityContext: {}
          volumeMounts: null
      securityContext:
        fsGroup: 1000
      serviceAccountName: stirling-pdf
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: stirling-pdf
