apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stirlingpdf.serviceAccountName" . }}
  labels:
    {{- include "stirlingpdf.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
