apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: stirling-pdf
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  externalTrafficPolicy: Local
  ports:
    - name: http
      nodePort: 30081
      port: 8080
      protocol: TCP
      targetPort: http
  type: NodePort
