apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: stirlingpdf
    app.kubernetes.io/name: stirlingpdf
    argocd.argoproj.io/instance: stirlingpdf
  name: stirling-pdf
  namespace: stirlingpdf
