apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: stirlingpdf
    app.kubernetes.io/name: stirlingpdf
    argocd.argoproj.io/instance: stirlingpdf
  name: stirling-pdf
  namespace: stirlingpdf
spec:
  externalTrafficPolicy: Local
  ports:
    - name: http
      nodePort: 30081
      port: 8080
      protocol: TCP
      targetPort: http
  type: NodePort
