apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: default 
  settings.yaml: |
   title: Home
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - My First Group:
      - Change-Detection:
          icon: changedetection.png
          href: https://allapps.me/changedetection
          widget:
            type: changedetectionio
            url: http://10.102.68.47:5000
            key: ae32ec94de392b6701f5e4e0088358f3
      - Argo-CD:
          icon: argo-cd.png
          href: https://allapps.me/argocd
          widget:
            type: argocd
            fields: ["apps", "healthy","synced","outOfSync"]
            url: http://10.106.46.16:80
            key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJyZWFkb25seTphcGlLZXkiLCJuYmYiOjE3MzcxMzU1NTcsImlhdCI6MTczNzEzNTU1NywianRpIjoiMDAxMmU5MTgtYmU2MC00OTAwLWI4YjctZDkzYjgzNGZkN2EwIn0.9TtoMaV9MD0VecLzkswbV5nSvM7hcPk5RYRpBHqoJo0
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: false
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: google
        target: _blank
  docker.yaml: ""