stirling-pdf-chart:
  fullnameOverride: stirling-pdf
  rootPath: /pdf
  service:
    type: NodePort
    nodePort: 30081
  pv:
    enabled: true
    capacity:
      storage: 1Gi
  persistence:
    enabled: true
    size: 1Gi
    path: configs
  envs:
    - name: ALLOW_GOOGLE_VISIBILITY
      value: "false"
    - name: APP_LOCALE
      value: "fr-FR"
    - name: SYSTEM_ENABLEANALYTICS
      value: "false"