argo-cd:
  fullnameOverride: argocd
  namespaceOverride: argocd
  server:
    service:
      type: NodePort
  configs:
    params:
      server.rootpath: "/argocd"
      server.basehref: "/argocd"
      server.insecure: true
      server.disable.auth: true
  dex:
    enabled: false
  notifications:
    enabled: false